seed: 21
ansible_pwd: "ansible-pwd.txt"

db:
  mssql_creds: "mssql-creds.yml"
  data_table: "Wines"
  metrics_table: "Metrics"

model:
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 1

experiments:
  dir: "experiments"
  save_to: "latest"