ansible_pwd: "ansible-pwd.txt"
db:
  mssql_creds: "mssql-creds.yml"
  data_table: "Wines"
  metrics_table: "Metrics"
data:
  train_data: data/train.csv
  val_data: data/val.csv
  test_data: data/test.csv

init_file: "create_db.sql"
