Started by user Boris Shaposhnikov
Obtained cd/Jenkinsfile from git https://github.com/borisshapa/wine-quality
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /var/jenkins_home/workspace/wine-quality-cd-pipeline
[Pipeline] {
[Pipeline] withCredentials
Masking supported pattern matches of $DOCKERHUB_CREDS or $DOCKERHUB_CREDS_PSW
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] timestamps
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Login)
[Pipeline] sh
[2023-05-21T11:07:16.467Z] Warning: A secret was passed to "sh" using Groovy String interpolation, which is insecure.
[2023-05-21T11:07:16.468Z] 		 Affected argument(s) used the following variable(s): [DOCKERHUB_CREDS_PSW]
[2023-05-21T11:07:16.468Z] 		 See https://jenkins.io/redirect/groovy-string-interpolation for details.
[2023-05-21T11:07:16.727Z] + docker login -u borisshapa -p ****
[2023-05-21T11:07:16.727Z] WARNING! Using --password via the CLI is insecure. Use --password-stdin.
[2023-05-21T11:07:18.590Z] WARNING! Your password will be stored unencrypted in /var/jenkins_home/.docker/config.json.
[2023-05-21T11:07:18.590Z] Configure a credential helper to remove this warning. See
[2023-05-21T11:07:18.590Z] https://docs.docker.com/engine/reference/commandline/login/#credentials-store
[2023-05-21T11:07:18.590Z]
[2023-05-21T11:07:18.590Z] Login Succeeded
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Pull image)
[Pipeline] sh
[2023-05-21T11:07:18.965Z] + docker pull borisshapa/wine-quality:latest
[2023-05-21T11:07:20.828Z] latest: Pulling from borisshapa/wine-quality
[2023-05-21T11:07:20.828Z] Digest: sha256:563275f4cec02efcca0b662b60f006d206345d59d79bb29656c09e4cc7776fad
[2023-05-21T11:07:20.828Z] Status: Image is up to date for borisshapa/wine-quality:latest
[2023-05-21T11:07:20.828Z] docker.io/borisshapa/wine-quality:latest
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Run tests)
[Pipeline] sh
[2023-05-21T11:07:21.203Z] + docker run --name wine-quality borisshapa/wine-quality:latest python -m scripts.run_tests
[2023-05-21T11:07:24.432Z] 2023-05-21 11:07:24.024 | INFO     | __main__:main:29 - Loading model from experiments/latest/model.cbm
[2023-05-21T11:07:24.432Z] 2023-05-21 11:07:24.118 | INFO     | __main__:main:38 - Running tests from test_0.json
[2023-05-21T11:07:24.432Z] 2023-05-21 11:07:24.122 | INFO     | __main__:main:48 - TEST 0 | features: [0, 12.4, 0.42, 0.49, 4.6, 0.073, 19.0, 43.0, 0.9978, 3.02, 0.61, 9.5]
[2023-05-21T11:07:24.432Z] 2023-05-21 11:07:24.122 | INFO     | __main__:main:57 - SUCCESS
[2023-05-21T11:07:24.432Z] 2023-05-21 11:07:24.123 | INFO     | __main__:main:38 - Running tests from test_1.json
[2023-05-21T11:07:24.432Z] 2023-05-21 11:07:24.124 | INFO     | __main__:main:48 - TEST 0 | features: [1, 6.8, 0.11, 0.27, 8.6, 0.044, 45.0, 104.0, 0.99454, 3.2, 0.37, 9.9]
[2023-05-21T11:07:24.432Z] 2023-05-21 11:07:24.124 | INFO     | __main__:main:57 - SUCCESS
[2023-05-21T11:07:24.432Z] 2023-05-21 11:07:24.124 | INFO     | __main__:main:60 - 2/2 test accepted
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] sh
[2023-05-21T11:07:25.106Z] + docker stop wine-quality
[2023-05-21T11:07:25.106Z] wine-quality
[2023-05-21T11:07:25.106Z] + docker rm wine-quality
[2023-05-21T11:07:25.106Z] wine-quality
[2023-05-21T11:07:25.106Z] + docker logout
[2023-05-21T11:07:25.106Z] Removing login credentials for https://index.docker.io/v1/
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
