pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials("borisshapa-docker-hub")
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {
        stage("Login"){
            steps {
                sh "docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW"
            }
        }
        stage("Pull image"){
            steps {
                sh "docker pull borisshapa/wine-quality:latest"
            }
        }

        stage("Run container"){
            steps {
                sh "docker run --name wine-quality -p 80:5556 -d borisshapa/wine-quality:latest"
            }
        }
	}

    post {
        always {
            sh "docker stop wine-quality && docker logout"
        }
    }
}
