pipeline {
    agent any

    enviroment {
        DOCKERHUB_CREDS=credentials("wine-quality")
        LC_ALL = "en_US.UTF-8"
        LANG = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
    }

    stages {
        stage("Clone github repository") {
            steps {
                cleanWs()
                sh "git clone -b master https://github.com/borisshapa/wine-quality"
                sh "cd wine-quality"
            }
        }
        stage("Login") {
            steps {
                sh "docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%"
            }
        }
        stage("Build and run docker container") {
            steps {
                script{
                    try {
                        sh "docker-compose build"
                    } finally {
                        sh "docker-compose ip -d"
                    }
                }
            }
        }
    }
}